application: superguardianmobile
version: 1
runtime: python
api_version: 1

handlers:
- url: /cron/.*
  script: guardianmobileinterface/cron.py
- url: /task/.*
  script: guardianmobileinterface/workers.py
- url: /api/.*
  script: guardianmobileinterface/api.py
- url: /admin/.*
  script: guardianmobileinterface/admin.py
