application: guardianmobile
version: 1
runtime: python
api_version: 1

handlers:
- url: /.*/?rss
  script: rssParser.xmlParser.py
- url: /.*/?json
  script: rssParser.json.py
- url: /
  static_dir: project

